---
- name: Update APT cache
  ansible.builtin.include_tasks: update.yml
- name: Upgrade APT packages
  ansible.builtin.include_tasks: upgrade.yml
- name: Install APT dependencies
  ansible.builtin.include_tasks: dependencies.yml
- name: Configure unattended upgrades
  ansible.builtin.include_tasks: unattended_upgrades.yml
