---
- name: Configure APT
  ansible.builtin.import_tasks: config.yml
  tags:
    - system
    - apt
    - config
    - apt-config

- name: Manage APT repositories and keys
  ansible.builtin.import_tasks: manage.yml
  tags:
    - system
    - apt
    - manage
    - apt-manage

- name: Install APT packages
  ansible.builtin.import_tasks: install.yml
  tags:
    - system
    - apt
    - install
    - apt-install
