---
name: Linting

on:
  push:
    branches:
      - master
      - main
  pull_request:
    branches:
      - master
      - main
  schedule:
    - cron: "0 7 * * 1"

jobs:
  call-linting:
    uses: telekom-mms/.github/.github/workflows/ansible-lint.yml@main
